### PR TITLE
Fix download buttons

### PR DESCRIPTION
**Pull request by tusindfryd**
The buttons did not work at all - now once clicked the page will scroll nicely to the right download section.
Also added a button for Linux users.

### CODE REVIEW

**Comment by timhoffm** [comment]
Actually, the `href` should directly link to some default downloads, e.g. the installer on windows. I assume something is broken in the script that generates these links.

**Comment by sunderme** [comment]
what happens now, when you press download now?

**Comment by tusindfryd** [comment]
I see. Well, as for now there is no action on pressing the button, so I figured that this could just be a quick solution - and when the scripts that generate the link are fixed, there shouldn't be any conflict anyway. Another thing is that maybe some users would like to see what they're downloading and choose the version they want before downloading starts.

**Comment by timhoffm** [comment]
Related: #797.

This has been fixed in another way. Anyway, thanks for the contribution!

**Pull request closed without merging**
